/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Thu Oct  9 12:51:03 2014. */

#include "proto.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool mindspy_protobufs_Request_stream_default = false;


const pb_field_t mindspy_protobufs_Separator_fields[2] = {
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , FIRST, mindspy_protobufs_Separator, last, last, 0),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_State_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, mindspy_protobufs_State, address, address, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, mindspy_protobufs_State, payload, address, 0),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_Sample_fields[3] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, mindspy_protobufs_Sample, sequence, sequence, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, mindspy_protobufs_Sample, payload, sequence, 0),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_GetSamples_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, mindspy_protobufs_GetSamples, count, count, 0),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_GetState_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, mindspy_protobufs_GetState, addresses, addresses, 0),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_SetState_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, mindspy_protobufs_SetState, states, states, &mindspy_protobufs_State_fields),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_GetModelName_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_Request_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, mindspy_protobufs_Request, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, mindspy_protobufs_Request, reqid, timestamp, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Request, module, reqid, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Request, stream, module, &mindspy_protobufs_Request_stream_default),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Request, getSamples, stream, &mindspy_protobufs_GetSamples_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Request, getState, getSamples, &mindspy_protobufs_GetState_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Request, setState, getState, &mindspy_protobufs_SetState_fields),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Request, getModelName, setState, &mindspy_protobufs_GetModelName_fields),
    PB_LAST_FIELD
};

const pb_field_t mindspy_protobufs_Response_fields[8] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, mindspy_protobufs_Response, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, mindspy_protobufs_Response, reqid, timestamp, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Response, module, reqid, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, mindspy_protobufs_Response, states, module, &mindspy_protobufs_State_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, mindspy_protobufs_Response, samples, states, &mindspy_protobufs_Sample_fields),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Response, modelName, samples, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, mindspy_protobufs_Response, error_msg, modelName, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(mindspy_protobufs_SetState, states[0]) < 65536 && pb_membersize(mindspy_protobufs_Request, getSamples) < 65536 && pb_membersize(mindspy_protobufs_Request, getState) < 65536 && pb_membersize(mindspy_protobufs_Request, setState) < 65536 && pb_membersize(mindspy_protobufs_Request, getModelName) < 65536 && pb_membersize(mindspy_protobufs_Response, states[0]) < 65536 && pb_membersize(mindspy_protobufs_Response, samples[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_mindspy_protobufs_Separator_mindspy_protobufs_State_mindspy_protobufs_Sample_mindspy_protobufs_GetSamples_mindspy_protobufs_GetState_mindspy_protobufs_SetState_mindspy_protobufs_GetModelName_mindspy_protobufs_Request_mindspy_protobufs_Response)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(mindspy_protobufs_SetState, states[0]) < 256 && pb_membersize(mindspy_protobufs_Request, getSamples) < 256 && pb_membersize(mindspy_protobufs_Request, getState) < 256 && pb_membersize(mindspy_protobufs_Request, setState) < 256 && pb_membersize(mindspy_protobufs_Request, getModelName) < 256 && pb_membersize(mindspy_protobufs_Response, states[0]) < 256 && pb_membersize(mindspy_protobufs_Response, samples[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_mindspy_protobufs_Separator_mindspy_protobufs_State_mindspy_protobufs_Sample_mindspy_protobufs_GetSamples_mindspy_protobufs_GetState_mindspy_protobufs_SetState_mindspy_protobufs_GetModelName_mindspy_protobufs_Request_mindspy_protobufs_Response)
#endif


