/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Wed Sep 24 19:09:57 2014. */

#include "proto.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool Request_stream_default = false;


const pb_field_t Separator_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Separator, size, size, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, Separator, last, size, 0),
    PB_LAST_FIELD
};

const pb_field_t State_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, State, address, address, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, State, payload, address, 0),
    PB_LAST_FIELD
};

const pb_field_t Sample_fields[3] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, Sample, sequence, sequence, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, Sample, payload, sequence, 0),
    PB_LAST_FIELD
};

const pb_field_t GetSamples_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, GetSamples, count, count, 0),
    PB_LAST_FIELD
};

const pb_field_t GetState_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, GetState, addresses, addresses, 0),
    PB_LAST_FIELD
};

const pb_field_t SetState_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, SetState, states, states, &State_fields),
    PB_LAST_FIELD
};

const pb_field_t GetModelName_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Request_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, Request, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Request, reqid, timestamp, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Request, module, reqid, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, Request, stream, module, &Request_stream_default),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, Request, getSamples, stream, &GetSamples_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, Request, getState, getSamples, &GetState_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, Request, setState, getState, &SetState_fields),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, Request, getModelName, setState, &GetModelName_fields),
    PB_LAST_FIELD
};

const pb_field_t Response_fields[8] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, Response, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Response, reqid, timestamp, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Response, module, reqid, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, Response, states, module, &State_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, Response, samples, states, &Sample_fields),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, Response, modelName, samples, 0),
    PB_FIELD(  7, STRING  , OPTIONAL, STATIC  , OTHER, Response, error_msg, modelName, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SetState, states[0]) < 65536 && pb_membersize(Request, getSamples) < 65536 && pb_membersize(Request, getState) < 65536 && pb_membersize(Request, setState) < 65536 && pb_membersize(Request, getModelName) < 65536 && pb_membersize(Response, states[0]) < 65536 && pb_membersize(Response, samples[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Separator_State_Sample_GetSamples_GetState_SetState_GetModelName_Request_Response)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SetState, states[0]) < 256 && pb_membersize(Request, getSamples) < 256 && pb_membersize(Request, getState) < 256 && pb_membersize(Request, setState) < 256 && pb_membersize(Request, getModelName) < 256 && pb_membersize(Response, states[0]) < 256 && pb_membersize(Response, samples[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Separator_State_Sample_GetSamples_GetState_SetState_GetModelName_Request_Response)
#endif


