/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.0 at Thu Oct  9 12:51:03 2014. */

#ifndef PB_MINDSPY_PB_H_INCLUDED
#define PB_MINDSPY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _mindspy_protobufs_GetModelName {
    uint8_t dummy_field;
} mindspy_protobufs_GetModelName;

typedef struct _mindspy_protobufs_GetSamples {
    uint32_t count;
} mindspy_protobufs_GetSamples;

typedef struct _mindspy_protobufs_GetState {
    pb_size_t addresses_count;
    uint32_t addresses[16];
} mindspy_protobufs_GetState;

typedef struct _mindspy_protobufs_Sample {
    uint64_t sequence;
    pb_size_t payload_count;
    int32_t payload[32];
} mindspy_protobufs_Sample;

typedef struct _mindspy_protobufs_Separator {
    bool last;
} mindspy_protobufs_Separator;

typedef struct _mindspy_protobufs_State {
    uint32_t address;
    uint32_t payload;
} mindspy_protobufs_State;

typedef struct _mindspy_protobufs_Response {
    uint64_t timestamp;
    uint32_t reqid;
    bool has_module;
    uint32_t module;
    pb_size_t states_count;
    mindspy_protobufs_State states[16];
    pb_size_t samples_count;
    mindspy_protobufs_Sample samples[16];
    bool has_modelName;
    char modelName[16];
    bool has_error_msg;
    char error_msg[64];
} mindspy_protobufs_Response;

typedef struct _mindspy_protobufs_SetState {
    pb_size_t states_count;
    mindspy_protobufs_State states[16];
} mindspy_protobufs_SetState;

typedef struct _mindspy_protobufs_Request {
    uint64_t timestamp;
    uint32_t reqid;
    bool has_module;
    uint32_t module;
    bool has_stream;
    bool stream;
    bool has_getSamples;
    mindspy_protobufs_GetSamples getSamples;
    bool has_getState;
    mindspy_protobufs_GetState getState;
    bool has_setState;
    mindspy_protobufs_SetState setState;
    bool has_getModelName;
    mindspy_protobufs_GetModelName getModelName;
} mindspy_protobufs_Request;

/* Default values for struct fields */
extern const bool mindspy_protobufs_Request_stream_default;

/* Initializer values for message structs */
#define mindspy_protobufs_Separator_init_default {0}
#define mindspy_protobufs_State_init_default     {0, 0}
#define mindspy_protobufs_Sample_init_default    {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define mindspy_protobufs_GetSamples_init_default {0}
#define mindspy_protobufs_GetState_init_default  {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define mindspy_protobufs_SetState_init_default  {0, {mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default}}
#define mindspy_protobufs_GetModelName_init_default {0}
#define mindspy_protobufs_Request_init_default   {0, 0, false, 0, false, false, false, mindspy_protobufs_GetSamples_init_default, false, mindspy_protobufs_GetState_init_default, false, mindspy_protobufs_SetState_init_default, false, mindspy_protobufs_GetModelName_init_default}
#define mindspy_protobufs_Response_init_default  {0, 0, false, 0, 0, {mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default, mindspy_protobufs_State_init_default}, 0, {mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default, mindspy_protobufs_Sample_init_default}, false, "", false, ""}
#define mindspy_protobufs_Separator_init_zero    {0}
#define mindspy_protobufs_State_init_zero        {0, 0}
#define mindspy_protobufs_Sample_init_zero       {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define mindspy_protobufs_GetSamples_init_zero   {0}
#define mindspy_protobufs_GetState_init_zero     {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define mindspy_protobufs_SetState_init_zero     {0, {mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero}}
#define mindspy_protobufs_GetModelName_init_zero {0}
#define mindspy_protobufs_Request_init_zero      {0, 0, false, 0, false, 0, false, mindspy_protobufs_GetSamples_init_zero, false, mindspy_protobufs_GetState_init_zero, false, mindspy_protobufs_SetState_init_zero, false, mindspy_protobufs_GetModelName_init_zero}
#define mindspy_protobufs_Response_init_zero     {0, 0, false, 0, 0, {mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero, mindspy_protobufs_State_init_zero}, 0, {mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero, mindspy_protobufs_Sample_init_zero}, false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define mindspy_protobufs_GetSamples_count_tag   1
#define mindspy_protobufs_GetState_addresses_tag 1
#define mindspy_protobufs_Sample_sequence_tag    1
#define mindspy_protobufs_Sample_payload_tag     2
#define mindspy_protobufs_Separator_last_tag     2
#define mindspy_protobufs_State_address_tag      1
#define mindspy_protobufs_State_payload_tag      2
#define mindspy_protobufs_Response_timestamp_tag 1
#define mindspy_protobufs_Response_reqid_tag     2
#define mindspy_protobufs_Response_module_tag    3
#define mindspy_protobufs_Response_states_tag    4
#define mindspy_protobufs_Response_samples_tag   5
#define mindspy_protobufs_Response_modelName_tag 6
#define mindspy_protobufs_Response_error_msg_tag 7
#define mindspy_protobufs_SetState_states_tag    1
#define mindspy_protobufs_Request_timestamp_tag  1
#define mindspy_protobufs_Request_reqid_tag      2
#define mindspy_protobufs_Request_module_tag     3
#define mindspy_protobufs_Request_stream_tag     4
#define mindspy_protobufs_Request_getSamples_tag 5
#define mindspy_protobufs_Request_getState_tag   6
#define mindspy_protobufs_Request_setState_tag   7
#define mindspy_protobufs_Request_getModelName_tag 8

/* Struct field encoding specification for nanopb */
extern const pb_field_t mindspy_protobufs_Separator_fields[2];
extern const pb_field_t mindspy_protobufs_State_fields[3];
extern const pb_field_t mindspy_protobufs_Sample_fields[3];
extern const pb_field_t mindspy_protobufs_GetSamples_fields[2];
extern const pb_field_t mindspy_protobufs_GetState_fields[2];
extern const pb_field_t mindspy_protobufs_SetState_fields[2];
extern const pb_field_t mindspy_protobufs_GetModelName_fields[1];
extern const pb_field_t mindspy_protobufs_Request_fields[9];
extern const pb_field_t mindspy_protobufs_Response_fields[8];

/* Maximum encoded size of messages (where known) */
#define mindspy_protobufs_Separator_size         2
#define mindspy_protobufs_State_size             12
#define mindspy_protobufs_Sample_size            363
#define mindspy_protobufs_GetSamples_size        6
#define mindspy_protobufs_GetState_size          96
#define mindspy_protobufs_SetState_size          224
#define mindspy_protobufs_GetModelName_size      0
#define mindspy_protobufs_Request_size           360
#define mindspy_protobufs_Response_size          6187

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
