/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.0 at Wed Sep 10 15:45:37 2014. */

#include "regs_pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool Request_stream_default = false;
const int32_t Request_module_default = -1;
const Response_ErrNo Response_error_default = Response_ErrNo_NO_ERROR;
const int32_t Response_module_default = -1;


const pb_field_t Request_fields[9] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, Request, action, action, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, Request, timestamp, action, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Request, start, timestamp, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, Request, count, start, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, Request, payload, count, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, Request, stream, payload, &Request_stream_default),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, Request, reqid, stream, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, Request, module, reqid, &Request_module_default),
    PB_LAST_FIELD
};

const pb_field_t State_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, State, address, address, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, State, payload, address, 0),
    PB_LAST_FIELD
};

const pb_field_t Sample_fields[3] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, Sample, sequence, sequence, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, Sample, payload, sequence, 0),
    PB_LAST_FIELD
};

const pb_field_t Response_fields[8] = {
    PB_FIELD(  1, ENUM    , OPTIONAL, STATIC  , FIRST, Response, error, error, &Response_error_default),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, Response, error_msg, error, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, Response, timestamp, error_msg, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, Response, state, timestamp, &State_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, Response, sample, state, &Sample_fields),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, Response, reqid, sample, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, Response, module, reqid, &Response_module_default),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Response, state) < 65536 && pb_membersize(Response, sample) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Request_State_Sample_Response)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Response, state) < 256 && pb_membersize(Response, sample) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Request_State_Sample_Response)
#endif


