# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='regs.proto',
  package='',
  serialized_pb='\n\nregs.proto\"\x19\n\tSeparator\x12\x0c\n\x04last\x18\x01 \x02(\x08\"\xe4\x01\n\x07Request\x12\x1f\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32\x0f.Request.Action\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\x15\n\x06stream\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\r\n\x05start\x18\x03 \x01(\r\x12\r\n\x05\x63ount\x18\x04 \x01(\r\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\"_\n\x06\x41\x63tion\x12\x08\n\x04\x45\x43HO\x10\x00\x12\r\n\tGET_STATE\x10\x02\x12\r\n\tSET_STATE\x10\x03\x12\x0b\n\x07SAMPLES\x10\x01\x12\x08\n\x04TEST\x10\x04\x12\x07\n\x03LED\x10\x05\x12\r\n\tSTIMULATE\x10\x06\")\n\x05State\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x02(\r\x12\x0f\n\x07payload\x18\x02 \x02(\r\"+\n\x06Sample\x12\x10\n\x08sequence\x18\x01 \x02(\x04\x12\x0f\n\x07payload\x18\x02 \x03(\x05\"\xca\x01\n\x08Response\x12(\n\x05\x65rror\x18\x01 \x01(\x0e\x32\x0f.Response.ErrNo:\x08NO_ERROR\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x02(\x04\x12\x15\n\x05state\x18\x04 \x03(\x0b\x32\x06.State\x12\x17\n\x06sample\x18\x05 \x03(\x0b\x32\x07.Sample\">\n\x05\x45rrNo\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x13\n\x0fHANDLER_MISSING\x10\x01\x12\x12\n\x0eHANDLER_FAILED\x10\x02')



_REQUEST_ACTION = descriptor.EnumDescriptor(
  name='Action',
  full_name='Request.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ECHO', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_STATE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SET_STATE', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SAMPLES', index=3, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TEST', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LED', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STIMULATE', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=175,
  serialized_end=270,
)

_RESPONSE_ERRNO = descriptor.EnumDescriptor(
  name='ErrNo',
  full_name='Response.ErrNo',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HANDLER_MISSING', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HANDLER_FAILED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=501,
  serialized_end=563,
)


_SEPARATOR = descriptor.Descriptor(
  name='Separator',
  full_name='Separator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='last', full_name='Separator.last', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=39,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='action', full_name='Request.action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='Request.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stream', full_name='Request.stream', index=2,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start', full_name='Request.start', index=3,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='Request.count', index=4,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='Request.payload', index=5,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_ACTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=270,
)


_STATE = descriptor.Descriptor(
  name='State',
  full_name='State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='address', full_name='State.address', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='State.payload', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=272,
  serialized_end=313,
)


_SAMPLE = descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sequence', full_name='Sample.sequence', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='Sample.payload', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=315,
  serialized_end=358,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='Response.error', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_msg', full_name='Response.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='Response.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='Response.state', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sample', full_name='Response.sample', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_ERRNO,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=361,
  serialized_end=563,
)

_REQUEST.fields_by_name['action'].enum_type = _REQUEST_ACTION
_REQUEST_ACTION.containing_type = _REQUEST;
_RESPONSE.fields_by_name['error'].enum_type = _RESPONSE_ERRNO
_RESPONSE.fields_by_name['state'].message_type = _STATE
_RESPONSE.fields_by_name['sample'].message_type = _SAMPLE
_RESPONSE_ERRNO.containing_type = _RESPONSE;
DESCRIPTOR.message_types_by_name['Separator'] = _SEPARATOR
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Separator(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEPARATOR
  
  # @@protoc_insertion_point(class_scope:Separator)

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:Request)

class State(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATE
  
  # @@protoc_insertion_point(class_scope:State)

class Sample(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE
  
  # @@protoc_insertion_point(class_scope:Sample)

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:Response)

# @@protoc_insertion_point(module_scope)
