/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.0 at Thu Sep 18 10:58:21 2014. */

#ifndef PB_REGS_PB_H_INCLUDED
#define PB_REGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _GetModelName {
    uint8_t dummy_field;
} GetModelName;

typedef struct _GetSamples {
    uint32_t count;
} GetSamples;

typedef struct _GetState {
    pb_size_t addresses_count;
    uint32_t addresses[16];
} GetState;

typedef struct _Sample {
    uint64_t sequence;
    pb_size_t payload_count;
    int32_t payload[8];
} Sample;

typedef struct _Separator {
    uint32_t size;
    bool last;
} Separator;

typedef struct _State {
    uint32_t address;
    uint32_t payload;
} State;

typedef struct _Response {
    uint64_t timestamp;
    uint32_t reqid;
    uint32_t module;
    pb_size_t states_count;
    State states[16];
    pb_size_t samples_count;
    Sample samples[16];
    bool has_modelName;
    char modelName[16];
    bool has_error_msg;
    char error_msg[64];
} Response;

typedef struct _SetState {
    pb_size_t states_count;
    State states[16];
} SetState;

typedef struct _Request {
    uint64_t timestamp;
    uint32_t reqid;
    bool has_module;
    uint32_t module;
    bool has_stream;
    bool stream;
    bool has_getSamples;
    GetSamples getSamples;
    bool has_getState;
    GetState getState;
    bool has_setState;
    SetState setState;
    bool has_getModelName;
    GetModelName getModelName;
} Request;

/* Default values for struct fields */
extern const bool Request_stream_default;

/* Initializer values for message structs */
#define Separator_init_default                   {0, 0}
#define State_init_default                       {0, 0}
#define Sample_init_default                      {0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define GetSamples_init_default                  {0}
#define GetState_init_default                    {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define SetState_init_default                    {0, {State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default}}
#define GetModelName_init_default                {0}
#define Request_init_default                     {0, 0, false, 0, false, false, false, GetSamples_init_default, false, GetState_init_default, false, SetState_init_default, false, GetModelName_init_default}
#define Response_init_default                    {0, 0, 0, 0, {State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default, State_init_default}, 0, {Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default}, false, "", false, ""}
#define Separator_init_zero                      {0, 0}
#define State_init_zero                          {0, 0}
#define Sample_init_zero                         {0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define GetSamples_init_zero                     {0}
#define GetState_init_zero                       {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define SetState_init_zero                       {0, {State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero}}
#define GetModelName_init_zero                   {0}
#define Request_init_zero                        {0, 0, false, 0, false, 0, false, GetSamples_init_zero, false, GetState_init_zero, false, SetState_init_zero, false, GetModelName_init_zero}
#define Response_init_zero                       {0, 0, 0, 0, {State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero, State_init_zero}, 0, {Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero}, false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define GetSamples_count_tag                     1
#define GetState_addresses_tag                   1
#define Sample_sequence_tag                      1
#define Sample_payload_tag                       2
#define Separator_size_tag                       1
#define Separator_last_tag                       2
#define State_address_tag                        1
#define State_payload_tag                        2
#define Response_timestamp_tag                   1
#define Response_reqid_tag                       2
#define Response_module_tag                      3
#define Response_states_tag                      4
#define Response_samples_tag                     5
#define Response_modelName_tag                   6
#define Response_error_msg_tag                   7
#define SetState_states_tag                      1
#define Request_timestamp_tag                    1
#define Request_reqid_tag                        2
#define Request_module_tag                       3
#define Request_stream_tag                       4
#define Request_getSamples_tag                   5
#define Request_getState_tag                     6
#define Request_setState_tag                     7
#define Request_getModelName_tag                 8

/* Struct field encoding specification for nanopb */
extern const pb_field_t Separator_fields[3];
extern const pb_field_t State_fields[3];
extern const pb_field_t Sample_fields[3];
extern const pb_field_t GetSamples_fields[2];
extern const pb_field_t GetState_fields[2];
extern const pb_field_t SetState_fields[2];
extern const pb_field_t GetModelName_fields[1];
extern const pb_field_t Request_fields[9];
extern const pb_field_t Response_fields[8];

/* Maximum encoded size of messages (where known) */
#define Separator_size                           8
#define State_size                               12
#define Sample_size                              99
#define GetSamples_size                          6
#define GetState_size                            96
#define SetState_size                            224
#define GetModelName_size                        0
#define Request_size                             360
#define Response_size                            1947

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
